In [1]:
import pandas as pd

In [16]:
all_adat_samples = pd.read_csv('../../data/excels/20260309_adat_data_samples_with_sample_info.csv')

In [11]:
mdacc_matched_samples = pd.read_excel('../../data/excels/matched MDACC proteomics with scores.xlsx')

In [12]:
mdacc_matched_samples.columns

Index(['matched_index', 'PROPHET_EDTA_MeasureId', 'STRECK_MeasureId', 'KitId',
       'notes', 'EDTA Score', 'Streck Score bridging v1', 'diff v1',
       'Streck Score bridging v2', 'diff v2'],
      dtype='object')

In [15]:
mdacc_matched_samples = mdacc_matched_samples[mdacc_matched_samples['STRECK_MeasureId'].str.startswith('OH2025_05')|mdacc_matched_samples['STRECK_MeasureId'].str.startswith('OH2026')]

In [19]:
all_adat_samples[all_adat_samples['MeasureId'].isin(mdacc_matched_samples['PROPHET_EDTA_MeasureId'])]

,MeasureId,Source,IsT0,Type,SubType,DateOfRun,PlateCode,AdatFile,PlateId,ScannerID,...,ANMLFractionUsed_0_005,ANMLFractionUsed_0_5,SampleNumber,Optional1,Optional2,SysId,SysIdSource,SubjectId,Indication,SampleCollectionDate
8956,OH2025_052_A3,OH,not relevant,Sample,PROPHET,2025-11-25,OH25_052,C:\Users\OrItzhaki\Oncohost DX/Shares - R&D/Da...,OH2025_052,SG21378706,...,0.813,0.917,17.0,ACSK381759-242075,PROPHET,NaN,NaN,NaN,NaN,NaN
9111,OH2025_054_G8,OH,not relevant,Sample,PROPHET,2025-12-10,OH25_054,C:\Users\OrItzhaki\Oncohost DX/Shares - R&D/Da...,OH2025_054,SG21378706,...,0.834,0.910,63.0,ACSK381759-242079,PROPHET,NaN,NaN,NaN,NaN,NaN
9126,OH2025_055_A5,OH,not relevant,Sample,PROPHET,2025-12-17,OH25_055,C:\Users\OrItzhaki\Oncohost DX/Shares - R&D/Da...,OH2025_055,SG21378706,...,0.861,0.848,33.0,ACSK381759-242080,PROPHET,NaN,NaN,NaN,NaN,NaN
9278,OH2026_001_B4,OH,Unknown,Sample,PROPHETIC,2026-01-07,OH26_001,C:\Users\OrItzhaki\Oncohost DX/Shares - R&D/Da...,OH2026_001,SG21378706,...,0.898,0.909,26.0,SA-26.0148,Trial,SA-26.0148,joined on sys_id with labguru,ACSK381759-242202,NSCLC,2025-12-19
9488,OH2026_005_B1,OH,not relevant,Sample,PROPHET,2026-02-04,OH26_005,C:\Users\OrItzhaki\Oncohost DX/Shares - R&D/Da...,OH2026_005,SG21378706,...,0.930,0.887,2.0,ACSK381759-242095,PROPHET,NaN,NaN,NaN,NaN,NaN
9490,OH2026_005_B3,OH,not relevant,Sample,PROPHET,2026-02-04,OH26_005,C:\Users\OrItzhaki\Oncohost DX/Shares - R&D/Da...,OH2026_005,SG21378706,...,0.834,0.662,18.0,ACSK381759-241860,PROPHET,NaN,NaN,NaN,NaN,NaN
9495,OH2026_005_C2,OH,not relevant,Sample,PROPHET,2026-02-04,OH26_005,C:\Users\OrItzhaki\Oncohost DX/Shares - R&D/Da...,OH2026_005,SG21378706,...,0.979,0.956,11.0,ACSK381759-242083,PROPHET,NaN,NaN,NaN,NaN,NaN
9514,OH2026_005_F3,OH,not relevant,Sample,PROPHET,2026-02-04,OH26_005,C:\Users\OrItzhaki\Oncohost DX/Shares - R&D/Da...,OH2026_005,SG21378706,...,0.979,0.927,22.0,ACSK381759-242199,PROPHET,NaN,NaN,NaN,NaN,NaN
9525,OH2026_005_H2,OH,not relevant,Sample,PROPHET,2026-02-04,OH26_005,C:\Users\OrItzhaki\Oncohost DX/Shares - R&D/Da...,OH2026_005,SG21378706,...,0.968,0.941,16.0,ACSK381759-241877,PROPHET,NaN,NaN,NaN,NaN,NaN
9544,OH2026_006_C3,OH,not relevant,Sample,PROPHET,2026-02-11,OH26_006,C:\Users\OrItzhaki\Oncohost DX/Shares - R&D/Da...,OH2026_006,SG21378706,...,0.893,0.867,19.0,ACSK381759-242466,PROPHET,NaN,NaN,NaN,NaN,NaN
9562,OH2026_006_F3,OH,not relevant,Sample,PROPHET,2026-02-11,OH26_006,C:\Users\OrItzhaki\Oncohost DX/Shares - R&D/Da...,OH2026_006,SG21378706,...,0.952,0.951,22.0,ACSK381759-242442,PROPHET,NaN,NaN,NaN,NaN,NaN
9578,OH2026_007_A1,OH,Unknown,Sample,PROPHETIC,2026-02-18,OH26_007,C:\Users\OrItzhaki\Oncohost DX/Shares - R&D/Da...,OH2026_007,SG21378706,...,0.995,0.927,1.0,SA-26.0520,Trial,SA-26.0520,joined on sys_id with labguru,ACSK381759-242441,NSCLC,2026-02-13
9626,OH2026_008_A1,OH,Unknown,Sample,PROPHETIC,2026-02-24,OH26_008,C:\Users\OrItzhaki\Oncohost DX/Shares - R&D/Da...,OH2026_008,SG21378706,...,0.973,0.979,1.0,SA-26.0523,Trial,SA-26.0523,joined on sys_id with labguru,ACSK382005-248547,NSCLC,2026-02-23
9679,OH2026_009_A6,OH,Unknown,Sample,PROPHETIC,2026-03-04,OH26_009,C:\Users\OrItzhaki\Oncohost DX/Shares - R&D/Da...,OH2026_009,SG21378706,...,0.797,0.900,41.0,SA-26.0561,Trial,SA-26.0561,joined on sys_id with labguru,ACSK382005-248609,NSCLC,2026-02-26
9702,OH2026_009_E5,OH,Unknown,Sample,PROPHETIC,2026-03-04,OH26_009,C:\Users\OrItzhaki\Oncohost DX/Shares - R&D/Da...,OH2026_009,SG21378706,...,0.979,0.875,37.0,SA-26.0560,Trial,SA-26.0560,joined on sys_id with labguru,ACSK382005-248608,NSCLC,2026-02-26
9703,OH2026_009_E6,OH,Unknown,Sample,PROPHETIC,2026-03-04,OH26_009,C:\Users\OrItzhaki\Oncohost DX/Shares - R&D/Da...,OH2026_009,SG21378706,...,0.995,0.913,45.0,SA-26.0562,Trial,SA-26.0562,joined on sys_id with labguru,ACSK382005-248544,NSCLC,2026-02-27
9721,OH2026_009_H6,OH,Unknown,Sample,PROPHETIC,2026-03-04,OH26_009,C:\Users\OrItzhaki\Oncohost DX/Shares - R&D/Da...,OH2026_009,SG21378706,...,0.979,0.950,48.0,SA-26.0563,Trial,SA-26.0563,joined on sys_id with labguru,ACSK382005-248545,NSCLC,2026-03-02

In [3]:
mdacc_samples = pd.read_excel('../../data/excels/matched MDACC proteomics with scores.xlsx')

In [4]:
mdacc_samples.shape

(41, 10)

In [5]:
adat_data = pd.read_csv('../../data/excels/20260309_adat_data_measurements.csv')

In [6]:
adat_data.shape

(10721, 7597)

In [8]:
mdacc_samples.head()

,matched_index,PROPHET_EDTA_MeasureId,STRECK_MeasureId,KitId,notes,EDTA Score,Streck Score bridging v1,diff v1,Streck Score bridging v2,diff v2
0,1,OH2025_038_C4,OH2025_038_A6,ACSK381759-241911,NaN,0.951754,0.942982,0.008772,NaN,NaN
1,2,OH2025_038_B3,OH2025_038_E1,ACSK381759-241859,NaN,0.298246,0.640351,-0.342105,NaN,NaN
2,3,OH2025_039_F1,OH2025_039_A1,ACSK381759-241866,NaN,0.600877,0.859649,-0.258772,NaN,NaN
3,31,OH2025_027_D4,OH2025_039_A3,3047682,NaN,NaN,NaN,0.000000,NaN,0.0
4,4,OH2025_039_C5,OH2025_039_B2,ACSK381759-241914,NaN,0.293860,0.701754,-0.407895,NaN,NaN

In [9]:
mdacc_samples[mdacc_samples['STRECK_MeasureId'].isin(adat_data['MeasureId'])]

,matched_index,PROPHET_EDTA_MeasureId,STRECK_MeasureId,KitId,notes,EDTA Score,Streck Score bridging v1,diff v1,Streck Score bridging v2,diff v2
0,1,OH2025_038_C4,OH2025_038_A6,ACSK381759-241911,NaN,0.951754,0.942982,0.008772,NaN,NaN
1,2,OH2025_038_B3,OH2025_038_E1,ACSK381759-241859,NaN,0.298246,0.640351,-0.342105,NaN,NaN
2,3,OH2025_039_F1,OH2025_039_A1,ACSK381759-241866,NaN,0.600877,0.859649,-0.258772,NaN,NaN
3,31,OH2025_027_D4,OH2025_039_A3,3047682,NaN,NaN,NaN,0.000000,NaN,0.000000
4,4,OH2025_039_C5,OH2025_039_B2,ACSK381759-241914,NaN,0.293860,0.701754,-0.407895,NaN,NaN
5,39,OH2025_023_B6,OH2025_039_B5,8397246,NaN,NaN,NaN,0.000000,NaN,0.000000
6,28,OH2025_029_E6,OH2025_039_C2,1704563,NaN,NaN,NaN,0.000000,NaN,0.000000
7,32,OH2025_019_H3,OH2025_039_C3,3671298,NaN,NaN,NaN,0.000000,NaN,0.000000
8,35,OH2025_036_A6,OH2025_039_C4,6132059,NaN,NaN,NaN,0.000000,NaN,0.000000
9,36,OH2025_029_B6,OH2025_039_D4,6920145,NaN,NaN,NaN,0.000000,NaN,0.000000
10,5,OH2025_039_B3,OH2025_039_E1,ACSK381759-241874,NaN,0.513158,0.684211,-0.171053,NaN,NaN
11,37,OH2025_036_F3,OH2025_039_E4,7261940,NaN,NaN,NaN,0.000000,NaN,0.000000
12,40,OH2025_017_B2,OH2025_039_E5,9063271,the STRECK failed QC,NaN,NaN,0.000000,NaN,0.000000
13,29,OH2025_017_F2,OH2025_039_F2,1849057,NaN,NaN,NaN,0.000000,NaN,0.000000
14,33,OH2025_014_E6,OH2025_039_F3,4928164,the STRECK failed QC,NaN,NaN,0.000000,NaN,0.000000
15,6,OH2025_039_F4,OH2025_039_G1,ACSK381759-241906,NaN,0.434211,0.478070,-0.043860,NaN,NaN
16,30,OH2025_019_A6,OH2025_039_G2,2456710,NaN,NaN,NaN,0.000000,NaN,0.000000
17,34,OH2025_017_A5,OH2025_039_H3,5182043,the STRECK failed QC,NaN,NaN,0.000000,NaN,0.000000
18,38,OH2025_014_C5,OH2025_039_H4,7302519,NaN,NaN,NaN,0.000000,NaN,0.000000
19,41,OH2025_035_C5,OH2025_039_H5,9513807,NaN,NaN,NaN,0.000000,NaN,0.000000
20,7,OH2025_041_A4,OH2025_041_B1,ACSK381759-242092,the STRECK failed QC,0.688596,0.736842,-0.048246,NaN,NaN
21,8,OH2025_043_H5,OH2025_043_G6,ACSK381759-242091,the STRECK failed QC,0.293860,0.469298,-0.175439,NaN,NaN
22,9,OH2025_047_A2,OH2025_047_B1,ACSK381759-242209,the STRECK failed QC,0.390351,0.828947,-0.438596,NaN,NaN
23,10,OH2025_047_D6,OH2025_047_F3,ACSK381759-242204,NaN,0.600877,0.807018,-0.206140,NaN,NaN
24,11,OH2025_052_A3,OH2025_052_H6,ACSK381759-242075,the STRECK failed QC,0.013158,0.175439,-0.162281,NaN,NaN
25,12,OH2025_054_G8,OH2025_054_A1,ACSK381759-242079,NaN,0.008772,0.127193,-0.118421,0.206140,-0.197368
26,13,OH2025_055_A5,OH2025_055_C1,ACSK381759-242080,NaN,0.039474,0.013158,0.026316,NaN,NaN
27,14,OH2026_001_B4,OH2025_057_A3,ACSK381759-242202,NaN,0.030702,NaN,0.030702,0.381579,-0.350877
28,17,OH2026_005_B3,OH2026_005_A2,ACSK381759-241860,NaN,NaN,NaN,0.000000,NaN,0.000000
29,16,OH2026_005_B1,OH2026_005_D1,ACSK381759-242095,NaN,NaN,NaN,0.000000,NaN,0.000000
30,18,OH2026_005_F3,OH2026_005_D2,ACSK381759-242199,NaN,NaN,NaN,0.000000,NaN,0.000000
31,15,OH2026_005_C2,OH2026_005_F1,ACSK381759-242083,the STRECK failed QC,NaN,NaN,0.000000,NaN,0.000000
32,19,OH2026_005_H2,OH2026_005_H1,ACSK381759-241877,NaN,NaN,NaN,0.000000,NaN,0.000000
33,20,OH2026_006_C3,OH2026_006_D2,ACSK381759-242466,the STRECK failed QC,NaN,NaN,0.000000,NaN,0.000000
34,21,OH2026_006_F3,OH2026_006_G4,ACSK381759-242442,NaN,NaN,NaN,0.000000,NaN,0.000000
35,22,OH2026_007_A1,OH2026_007_E5,ACSK381759-242441,NaN,NaN,NaN,0.000000,NaN,0.000000
36,23,OH2026_008_A1,OH2026_008_D6,ACSK382005-248547,NaN,NaN,NaN,0.000000,NaN,0.000000
37,24,OH2026_009_A6,OH2026_009_B3,ACSK382005-248609,NaN,NaN,NaN,0.000000,NaN,0.000000
38,26,OH2026_009_E6,OH2026_009_D5,ACSK382005-248544,NaN,NaN,NaN,0.000000,NaN,0.000000
39,27,OH2026_009_H6,OH2026_009_G6,ACSK382005-248545,NaN,NaN,NaN,0.000000,NaN,0.000000
40,25,OH2026_009_E5,OH2026_009_H2,ACSK382005-248608,NaN,NaN,NaN,0.000000,NaN,0.000000